const sampleData = [
  {
    name: "Creative",
    engaged: 31,
    unique: 25,
    acquired: 84,
    conversion: "13%",
    id: 1,
  },
  {
    name: "Solutions",
    engaged: 63,
    unique: 32,
    acquired: 72,
    conversion: "9%",
    id: 2,
  },
  {
    name: "Integration",
    engaged: 97,
    unique: 20,
    acquired: 63,
    conversion: "17%",
    id: 3,
  },
  {
    name: "Research",
    engaged: 70,
    unique: 45,
    acquired: 88,
    conversion: "2%",
    id: 4,
  },
  {
    name: "Interactions",
    engaged: 82,
    unique: 15,
    acquired: 59,
    conversion: "18%",
    id: 5,
  },
  {
    name: "Paradigm",
    engaged: 51,
    unique: 4,
    acquired: 74,
    conversion: "11%",
    id: 6,
  },
  {
    name: "Response",
    engaged: 80,
    unique: 14,
    acquired: 67,
    conversion: "11%",
    id: 7,
  },
  {
    name: "Creative",
    engaged: 28,
    unique: 36,
    acquired: 63,
    conversion: "8%",
    id: 8,
  },
  {
    name: "Solutions",
    engaged: 79,
    unique: 45,
    acquired: 55,
    conversion: "11%",
    id: 9,
  },
  {
    name: "Research",
    engaged: 30,
    unique: 30,
    acquired: 71,
    conversion: "12%",
    id: 10,
  },
  {
    name: "Solutions",
    engaged: 61,
    unique: 36,
    acquired: 86,
    conversion: "8%",
    id: 11,
  },
  {
    name: "Research",
    engaged: 80,
    unique: 4,
    acquired: 60,
    conversion: "1%",
    id: 12,
  },
  {
    name: "Integration",
    engaged: 37,
    unique: 15,
    acquired: 92,
    conversion: "10%",
    id: 13,
  },
  {
    name: "Creative",
    engaged: 71,
    unique: 27,
    acquired: 64,
    conversion: "11%",
    id: 14,
  },
  {
    name: "Paradigm",
    engaged: 58,
    unique: 33,
    acquired: 68,
    conversion: "7%",
    id: 15,
  },
  {
    name: "Intranet",
    engaged: 53,
    unique: 21,
    acquired: 52,
    conversion: "8%",
    id: 16,
  },
  {
    name: "Solutions",
    engaged: 71,
    unique: 25,
    acquired: 72,
    conversion: "19%",
    id: 17,
  },
  {
    name: "Response",
    engaged: 37,
    unique: 26,
    acquired: 86,
    conversion: "6%",
    id: 18,
  },
  {
    name: "Paradigm",
    engaged: 75,
    unique: 39,
    acquired: 95,
    conversion: "9%",
    id: 19,
  },
  {
    name: "Solutions",
    engaged: 46,
    unique: 3,
    acquired: 66,
    conversion: "11%",
    id: 20,
  },
  {
    name: "Intranet",
    engaged: 84,
    unique: 10,
    acquired: 100,
    conversion: "6%",
    id: 21,
  },
  {
    name: "Response",
    engaged: 20,
    unique: 39,
    acquired: 62,
    conversion: "10%",
    id: 22,
  },
  {
    name: "Intranet",
    engaged: 40,
    unique: 28,
    acquired: 60,
    conversion: "2%",
    id: 23,
  },
  {
    name: "Response",
    engaged: 13,
    unique: 38,
    acquired: 52,
    conversion: "19%",
    id: 24,
  },
  {
    name: "Research",
    engaged: 63,
    unique: 46,
    acquired: 84,
    conversion: "16%",
    id: 25,
  },
  {
    name: "Interactions",
    engaged: 98,
    unique: 28,
    acquired: 72,
    conversion: "6%",
    id: 26,
  },
  {
    name: "Creative",
    engaged: 79,
    unique: 39,
    acquired: 82,
    conversion: "7%",
    id: 27,
  },
  {
    name: "Solutions",
    engaged: 70,
    unique: 4,
    acquired: 50,
    conversion: "1%",
    id: 28,
  },
  {
    name: "Research",
    engaged: 82,
    unique: 31,
    acquired: 53,
    conversion: "14%",
    id: 29,
  },
  {
    name: "Interactions",
    engaged: 17,
    unique: 7,
    acquired: 67,
    conversion: "14%",
    id: 30,
  },
  {
    name: "Solutions",
    engaged: 29,
    unique: 22,
    acquired: 62,
    conversion: "12%",
    id: 31,
  },
  {
    name: "Integration",
    engaged: 69,
    unique: 50,
    acquired: 79,
    conversion: "19%",
    id: 32,
  },
  {
    name: "Intranet",
    engaged: 31,
    unique: 10,
    acquired: 63,
    conversion: "19%",
    id: 33,
  },
  {
    name: "Paradigm",
    engaged: 46,
    unique: 41,
    acquired: 59,
    conversion: "15%",
    id: 34,
  },
  {
    name: "Integration",
    engaged: 29,
    unique: 16,
    acquired: 69,
    conversion: "13%",
    id: 35,
  },
  {
    name: "Paradigm",
    engaged: 57,
    unique: 33,
    acquired: 50,
    conversion: "18%",
    id: 36,
  },
  {
    name: "Response",
    engaged: 71,
    unique: 19,
    acquired: 97,
    conversion: "5%",
    id: 37,
  },
  {
    name: "Response",
    engaged: 70,
    unique: 16,
    acquired: 89,
    conversion: "6%",
    id: 38,
  },
  {
    name: "Solutions",
    engaged: 55,
    unique: 26,
    acquired: 90,
    conversion: "1%",
    id: 39,
  },
  {
    name: "Intranet",
    engaged: 12,
    unique: 22,
    acquired: 51,
    conversion: "18%",
    id: 40,
  },
  {
    name: "Intranet",
    engaged: 52,
    unique: 38,
    acquired: 76,
    conversion: "6%",
    id: 41,
  },
  {
    name: "Integration",
    engaged: 33,
    unique: 5,
    acquired: 98,
    conversion: "20%",
    id: 42,
  },
  {
    name: "Solutions",
    engaged: 42,
    unique: 27,
    acquired: 89,
    conversion: "13%",
    id: 43,
  },
  {
    name: "Intranet",
    engaged: 69,
    unique: 26,
    acquired: 58,
    conversion: "2%",
    id: 44,
  },
  {
    name: "Research",
    engaged: 64,
    unique: 38,
    acquired: 56,
    conversion: "11%",
    id: 45,
  },
  {
    name: "Interactions",
    engaged: 87,
    unique: 13,
    acquired: 56,
    conversion: "19%",
    id: 46,
  },
  {
    name: "Research",
    engaged: 37,
    unique: 6,
    acquired: 75,
    conversion: "18%",
    id: 47,
  },
  {
    name: "Solutions",
    engaged: 40,
    unique: 23,
    acquired: 62,
    conversion: "15%",
    id: 48,
  },
  {
    name: "Intranet",
    engaged: 38,
    unique: 40,
    acquired: 65,
    conversion: "17%",
    id: 49,
  },
  {
    name: "Integration",
    engaged: 81,
    unique: 13,
    acquired: 69,
    conversion: "20%",
    id: 50,
  },
];
export default sampleData;
